version: '3.1'

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_DB=herois
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
